Fix bug no2
OkiokData/SmartHashCat pull request #5
Opened 2019-02-24 22:21 UTC by tristandostaler

Fixed bug no2 by assuming the rockyou.txt downloaded at the setup step is the better one.

2019-02-25 00:49 UTC, mlahaye811 requested changes
To keep things simple, and because rockyou is not included in the "wordlist" of all distros (e.g. Ubuntu), I suggest to keep only "/usr/share/SmartHashCat/lists/rockyou.txt".

2019-02-25 00:51 UTC, mlahaye811 approved these changes

2019-02-25 00:52 UTC, mlahaye811 approved these changes

2019-03-01 16:50 UTC, tristandostaler commented
As discussed in person, I will drop this PR as we will update the setup.sh instead and use a symlink if the rockyou.txt file is already present.

2019-03-01 16:50 UTC, closed without merging